//<autogenerated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace DownloadData.Migrations
{
    /// <inheritdoc />
    public partial class AdicionaSetores : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "SectorId",
                table: "Industries",
                type: "integer",
                nullable: false,
                defaultValue: 12);

            migrationBuilder.CreateTable(
                name: "Sector",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "VARCHAR", maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Sector", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Sector",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Varejo" },
                    { 2, "Alimentos" },
                    { 3, "Commodities" },
                    { 4, "Indústria" },
                    { 5, "Energia" },
                    { 6, "Financeiro" },
                    { 7, "Telecomunicações" },
                    { 8, "Saúde" },
                    { 9, "Transporte" },
                    { 10, "Utilidade Pública" },
                    { 11, "Imobiliário" },
                    { 12, "Outros" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Industries_SectorId",
                table: "Industries",
                column: "SectorId");

            migrationBuilder.AddForeignKey(
                name: "FK_Industries_Sector_SectorId",
                table: "Industries",
                column: "SectorId",
                principalTable: "Sector",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Industries_Sector_SectorId",
                table: "Industries");

            migrationBuilder.DropTable(
                name: "Sector");

            migrationBuilder.DropIndex(
                name: "IX_Industries_SectorId",
                table: "Industries");

            migrationBuilder.DropColumn(
                name: "SectorId",
                table: "Industries");
        }
    }
}
