//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DownloadData.Migrations
{
    /// <inheritdoc />
    public partial class AddDividends : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Dividends",
                columns: table => new
                {
                    TickerId = table.Column<int>(type: "int", nullable: false),
                    ApprovalDate = table.Column<DateTime>(type: "DATE", nullable: false),
                    PriorExDate = table.Column<DateTime>(type: "DATE", nullable: false),
                    ClosePrice = table.Column<double>(type: "float", nullable: false),
                    DividendType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DividendsPercentage = table.Column<double>(type: "float", nullable: false),
                    DividendsValue = table.Column<double>(type: "float", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Dividends", x => new { x.TickerId, x.ApprovalDate });
                    table.ForeignKey(
                        name: "FK_Dividends_Tickers_TickerId",
                        column: x => x.TickerId,
                        principalTable: "Tickers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Dividends");
        }
    }
}
