//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DownloadData.Migrations
{
    /// <inheritdoc />
    public partial class AddSplitsAndSubscriptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Splits",
                columns: table => new
                {
                    TickerId = table.Column<int>(type: "int", nullable: false),
                    LastDate = table.Column<DateTime>(type: "DATE", nullable: false),
                    SplitFactor = table.Column<double>(type: "float", nullable: false),
                    ApprovalDate = table.Column<DateTime>(type: "DATE", nullable: false),
                    Type = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Splits", x => new { x.TickerId, x.LastDate });
                    table.ForeignKey(
                        name: "FK_Splits_Tickers_TickerId",
                        column: x => x.TickerId,
                        principalTable: "Tickers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Subscriptions",
                columns: table => new
                {
                    TickerId = table.Column<int>(type: "int", nullable: false),
                    LastDate = table.Column<DateTime>(type: "DATE", nullable: false),
                    Percentage = table.Column<double>(type: "float", nullable: false),
                    PriceUnit = table.Column<double>(type: "float", nullable: false),
                    ApprovalDate = table.Column<DateTime>(type: "DATE", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Subscriptions", x => new { x.TickerId, x.LastDate });
                    table.ForeignKey(
                        name: "FK_Subscriptions_Tickers_TickerId",
                        column: x => x.TickerId,
                        principalTable: "Tickers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Splits");

            migrationBuilder.DropTable(
                name: "Subscriptions");
        }
    }
}
