//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace DownloadData.Migrations
{
    /// <inheritdoc />
    public partial class ModificaSetores : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 1,
                column: "Name",
                value: "Agronegócio");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 2,
                column: "Name",
                value: "Bens Industriais");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 4,
                column: "Name",
                value: "Consumo cíclico");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 5,
                column: "Name",
                value: "Consumo não-cíclico");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 6,
                column: "Name",
                value: "Energia Elétrica");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 7,
                column: "Name",
                value: "Financeiro");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 8,
                column: "Name",
                value: "Imobiliário");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 9,
                column: "Name",
                value: "Industrial");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 10,
                column: "Name",
                value: "Materiais básicos");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 11,
                column: "Name",
                value: "Saúde");

            migrationBuilder.InsertData(
                table: "Sector",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 13, "Telecomunicações" },
                    { 14, "Transporte" },
                    { 15, "Utilidade Pública" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 13);

            migrationBuilder.DeleteData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 14);

            migrationBuilder.DeleteData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 15);

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 1,
                column: "Name",
                value: "Varejo");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 2,
                column: "Name",
                value: "Alimentos");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 4,
                column: "Name",
                value: "Indústria");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 5,
                column: "Name",
                value: "Energia");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 6,
                column: "Name",
                value: "Financeiro");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 7,
                column: "Name",
                value: "Telecomunicações");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 8,
                column: "Name",
                value: "Saúde");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 9,
                column: "Name",
                value: "Transporte");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 10,
                column: "Name",
                value: "Utilidade Pública");

            migrationBuilder.UpdateData(
                table: "Sector",
                keyColumn: "Id",
                keyValue: 11,
                column: "Name",
                value: "Imobiliário");
        }
    }
}
